name: Manual Test

on:
  workflow_dispatch:
    inputs:
      test_message:
        description: 'A test message'
        required: false
        default: 'Hello World'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: echo "${{ inputs.test_message }}"
      - name: Create test artifact
        run: echo "Test artifact content" > test-file.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-artifact
          path: test-file.txt
