name: Manual Test

on:
  workflow_dispatch:
    inputs:
      test_message:
        description: 'A test message'
        required: false
        default: 'Hello World'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: echo "${{ inputs.test_message }}"
